### ISSUE TITLE
IllegalArgumentException during connection.removeAllControlPoints();

### ISSUE THREAD

**Issue by BenJanus** [eclipse-gef/gef#91]
If you call `org.eclipse.gef.fx.nodes.Connection.removeAllControlPoints()` in a certain situation an `IllegalArgumentException `is thrown.

[RouterExample.java.txt](https://github.com/eclipse/gef/files/4393832/RouterExample.java.txt)

```
Caused by: java.lang.IllegalArgumentException: Index out of range (index: 1, size: 1).
	at org.eclipse.gef.fx.nodes.Connection.removeControlPoint(Connection.java:1499)
	at org.eclipse.gef.fx.nodes.Connection.removeAllControlPoints(Connection.java:1391)
	at com.initka.nui.gef.core.development.RouterExample.initConnection(RouterExample.java:71)
```

We are using version 5.0.1

**Comment by mwienand** [comment]
Thank you for reporting the issue!

I could easily reproduce the error using your example => Creating a test and debugging the issue right now.

First insight: the reason seems to be that removeControlPoint(index) might lead to more than the given control point being removed due to routing.

Possible solution: keep track of anchorsByKeys.size. Maybe I can find a nicer solution though.
